BurgerShop/Areas/Customer/Controllers/CustomerManagementController.cs
using BurgerShop.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BurgerShop.Areas.Customer.Controllers
{
    public class CustomerManagementController : CustomerBaseController
    {
        private readonly BurgerShopDbContext _db;
        private readonly UserManager<BurgerShopUser> _userManager;

        public CustomerManagementController(BurgerShopDbContext db, UserManager<BurgerShopUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var customerId = _userManager.GetUserId(User);
            var customer = _db.Users.Find(customerId);
            var orders = _db.Orders.Where(o => o.BurgerShopUserId == customerId).Include(o => o.Menus).Include(o => o.ExtraMaterials).ToList();

            ViewBag.CustomerName = $"{customer!.FirstName} {customer.LastName}";

            return View(orders);
        }
    }
}

BurgerShop/Areas/Manager/Controllers/ManagementController.cs
using BurgerShop.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BurgerShop.Areas.Manager.Controllers
{
    public class ManagementController : ManagerBaseController
    {
        private readonly BurgerShopDbContext _db;
        private readonly UserManager<BurgerShopUser> _userManager;

        public ManagementController(BurgerShopDbContext db, UserManager<BurgerShopUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var customers = _db.Users.Include(u => u.Orders).ThenInclude(o => o.Menus).Include(u => u.Orders).ThenInclude(o => o.ExtraMaterials).Where(u => u.Email != "manager@manager.com" && u.Orders.Count > 0).ToList();

            ViewBag.CustomerCount = _db.Users.Count() - 1;
            ViewBag.OrderCount = _db.Orders.Count();

            return View(customers);
        }
    }
}

BurgerShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>CraveWave Burgers | @ViewBag.Title</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/logo-white-trans.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Bootstrap-Select CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/css/bootstrap-select.min.css" integrity="sha512-mR/b5Y7FRsKqrYZou7uysnOdCIJib/7r5QeJMFvLNHNhtye3xJp1TdJVPLtetkukFn227nKpXD9OjUc09lx97Q==" crossorigin="anonymous"
          referrerpolicy="no-referrer" />

    <!-- Vendor CSS Files -->
    <link href="~/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">


    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Restaurantly
    * Updated: Jul 27 2023 with Bootstrap v5.3.1
    * Template URL: https://bootstrapmade.com/restaurantly-restaurant-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex justify-content-center justify-content-md-between">

            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-phone d-flex align-items-center"><span>+90 312 888 8888</span></i>
                <i class="bi bi-clock d-flex align-items-center ms-4"><span> Mon-Sat: 11AM - 23PM</span></i>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
            <div class="d-flex gap-4 align-items-center">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="logo me-lg-0"><img src="~/img/logo-white-trans.png" alt="" class="img-fluid"></a>
                <h1 class="logo  me-lg-0"><a asp-area="" asp-controller="Home" asp-action="Index">CraveWave Burgers</a></h1>
            </div>
            <!-- Uncomment below if you prefer to use an image logo -->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul class="gap-3">
                    <li><a class="nav-link scrollto" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#menu">Menu</a></li>
                    <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                    @if (User.IsInRole("Manager"))
                    {
                        <li><a class="nav-link scrollto fw-bold" asp-area="Manager" asp-controller="Management" asp-action="Index">Management</a></li>
                    }
                    else if (User.IsInRole("Customer"))
                    {
                        <li><a class="nav-link scrollto fw-bold" asp-area="Customer" asp-controller="CustomerManagement" asp-action="Index">Profile</a></li>
                    }
                    <partial name="_LoginPartial" />
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header><!-- End Header -->
    <div>@RenderBody()</div>
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="footer-info">
                            <h3>CraveWave Burgers</h3>
                            <p>
                                Ankara Teknoloji Geliştirme Bölgesi, G Blok, Üniversiteler Mahallesi Beytepe Lodumlu Köy Yolu Caddesi No:91, 06800 Çankaya/Ankara<br><br>
                                <strong>Phone:</strong> +90 312 888 8888<br>
                                <strong>Email:</strong> info@example.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>                  
                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                Copyright &copy; @DateTime.Now.Year <strong><span>CraveWave Burgers</span></strong>. All Rights Reserved
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>

    <!-- Bootstrap Select -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js" integrity="sha512-FHZVRMUW9FsXobt+ONiix6Z0tIkxvQfxtCSirkKc5Sb4TKHmqq1dZa8DphF0XqKb3ldLu/wgMa8mT6uXiLlRlw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>

</html>